spring:
  mail:
    host: smtp.gmail.com
    username: nirajsonu7@gmail.com
    password: wmyt xoic bibh jsmg
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true